### ISSUE TITLE
Tagging of episodes

### ISSUE THREAD

**Issue by woolfg** [EngineeringKiosk/webpage#143]
I propose to reduce the number of tags as it doesn't make sense to have tags that won't have more than one assigned episode in the near future. Especially for the user it is disappointing and for Google it is not relevant it processes the shownotes anyways. 

I propose to:
- delete: podcast, home-automation, Configuration Management, Eigener Job, Static Site Generator, Infrastructure as Code, Website, SQL, NOSQL, Cloud, INcident Management, Qualit\u00e4t
- rename: Interview -> Bewerbung

**Comment by andygrunwald** [comment]
#143 looks good!
