### ISSUE TITLE
Feedback of Wolfgang for PR #1

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#2]
Early feedback for https://github.com/EngineeringKiosk/webpage/pull/1

**Comment by woolfg** [comment]
- should we maybe switch the main color from orange to something blueish to match the preview images of the podcast
- parse episode description and link timestamps (supported by player?)

- [ ] Replace main image with mic image in front of kiosk
- [ ] Wer hält den Kiosk am laufem? -> am Laufen
- [ ] Change wording "subscribe" -> "follow" or "folgen"
- [ ] remove newletter or implement newsletter
- [ ] curently title "Don's Blog"
- [ ]  replace current logo with podcast mic and simple engineering kiosk text
- [ ] mobile/responsive burger menu doesn't work
- [ ] bullet points in episode description are not aligned (move to right)
- [ ] imprint
- [ ] remove/adapt footer menu

**Comment by andygrunwald** [comment]
## Under discussion

> should we maybe switch the main color from orange to something blueish to match the preview images of the podcast

I like the main color orange. I even thinking about switching it to yellow like in this template: https://podcastxtemplate.webflow.io/
I would not switch it to blueish.

## What is fixed

> Wer hält den Kiosk am laufem? -> am Laufen

Fixed in https://github.com/EngineeringKiosk/webpage/commit/8983926067206e2093a438ab39c193f4c2652e55

> Change wording "subscribe" -> "follow" or "folgen"

Fixed in https://github.com/EngineeringKiosk/webpage/commit/2e67bba780cc11caab0cfb0b4628b0c2c086d217

> curently title "Don's Blog"

Fixed in https://github.com/EngineeringKiosk/webpage/commit/7c4c1546b6c55745ad11cae2ea87dd51a3564d4b

> mobile/responsive burger menu doesn't work

Fixed in https://github.com/EngineeringKiosk/webpage/commit/fbc4cf28f78e6fcd7b444cb9940a19b4a40ebe12

> bullet points in episode description are not aligned (move to right)

Fixed in https://github.com/EngineeringKiosk/webpage/commit/1879d114e45f3cc7408a785324ae8c89436f93f0

> remove/adapt footer menu

Fixed in https://github.com/EngineeringKiosk/webpage/commit/4ba95f07667bd0572c66d7eac6cb1aeb2c9ed9e6

## Still TODO

> parse episode description and link timestamps (supported by player?)

TODO

> Replace main image with mic image in front of kiosk

TODO

> remove newsletter or implement newsletter

TODO

> replace current logo with podcast mic and simple engineering kiosk text

TODO

> imprint

TODO

**Comment by andygrunwald** [comment]
## What is fixed

> remove newsletter or implement newsletter

Fixed in https://github.com/EngineeringKiosk/webpage/commit/5f97d8bffda4d64f00b45a67e09e7f23c7898f2f

## Still TODO

> parse episode description and link timestamps (supported by player?)

TODO

> Replace main image with mic image in front of kiosk

TODO

> replace current logo with podcast mic and simple engineering kiosk text

TODO

> imprint

TODO

**Comment by andygrunwald** [comment]
## What is fixed / split up into own issues

> parse episode description and link timestamps (supported by player?)

See https://github.com/EngineeringKiosk/webpage/issues/10

> Replace main image with mic image in front of kiosk

See https://github.com/EngineeringKiosk/webpage/issues/6

> replace current logo with podcast mic and simple engineering kiosk text

See https://github.com/EngineeringKiosk/webpage/issues/5

> imprint

See https://github.com/EngineeringKiosk/webpage/issues/7
