### ISSUE TITLE
Listen on icons/links

### ISSUE THREAD

**Issue by woolfg** [EngineeringKiosk/webpage#21]
Users who discover the page via e.g. Google should be able to listen to episodes as easily as possible in their native podcast app. When they listen to an episode in their native prefered app, it is a war more likely that they will subscribe to the podcast. Therefore, this is crucial for an initial start.

- on main page (not only at the bottom via follow but also on top)
- on all episode pages

Icons are often not very well recognized. E.g. I have no clue how pocket casts or spoitfy look like, so it is better to use text for it, even though it is not that pretty.

Services that should be included:
- Google
- Apple
- Spotify
- Pocket Casts
- Castro
- Overcast
- RSS Feed

https://podwatch.io/podcast-apps-podcatcher/

**Comment by andygrunwald** [comment]
Goal of this task:
Adding sharing links like "listen on Spotify", "listen on Google Podcasts" on the episode detail view.

**Comment by andygrunwald** [comment]
I suggest we limit the choice and focus on the big ones:

- Spotify
- Google Podcast
- Apple Podcast
- Amazon Music
- Pocket Casts
- Direct download

**Comment by andygrunwald** [comment]
Skipped Pocket Casts, because the dont have a web view. Skipped direct downloads, because we aim to get followers on the platforms itself.

Looks like this now:

![Image](https://user-images.githubusercontent.com/320064/170825537-a63f341b-cc58-4b2c-ae73-025f614ec97b.png)
