### ISSUE TITLE
Improve SEO of German Tech Podcasts

### ISSUE THREAD

**Issue by woolfg** [EngineeringKiosk/webpage#230]
- [ ] change meta tag image on tag pages from hosts to `https://engineeringkiosk.dev/images/headers/german-tech-podcasts-head.jpeg`
- [ ] tag title from `Deutschsprachige Tech Podcasts zum Thema Datenschutz - Engineering Kiosk` to `Die besten Dateschutz Tech-Podcasts kuratiert im Engineering Kiosk`
- [ ] change title on overview `Deutschsprachige Tech Podcasts - Engineering Kiosk` to `Die besten Deutschsprachigen Tech Podcasts kuratiert im Engineering Kiosk`
- [ ] overview description: `Eine handverlesene Liste der besten deutschsprachigen Tech Podcasts zu relevanten Themen für Entwickler:innen, Tech-Leads und Nerds.`

General rules for meta tags:

- Keep your title length around 60 characters.
- For your meta description length, keep it around 160 characters.

**Comment by andygrunwald** [comment]
@woolfg I assume you were also referring to the overview page's HTML tags title and description.

See the three commits that are referenced here. Change is now live.

**Comment by woolfg** [comment]
thanks
