### ISSUE TITLE
German Tech Podcasts "Kiosk" Section

### ISSUE THREAD

**Issue by woolfg** [EngineeringKiosk/webpage#3]
Idee:
sowas wie https://analysis-tools.dev/ aber für deutsche tech podcasts und wir machen keine eigene website, sondern eine section auf unserer webseite die "tech kiosk" oder so heißt, und dort listen wir alle deutschen tech podcasts. eben ein "kiosk" (bild)

![image](https://user-images.githubusercontent.com/1328269/168058205-40315d87-f25a-482e-86ef-e2ff667f70f4.png)

Vorteile:
- SEO
- Reichweite und Kontakte zu anderen Podcastern (Eventueller Start für Community of Podcasters)

Umsetzung:
- Eventuell wie https://analysis-tools.dev/ (mre)
- Json/MD files in Github Repo?
- PRs um neue Podcasts hinzuzufügen

**Comment by woolfg** [comment]
https://github.com/EngineeringKiosk/GermanTechPodcasts created.

Next steps:
- [ ] Define main format (yaml, json?): my pref would be json
- [ ] Create process to create readme automatically from json files
- [ ] Fill readme with basic information

**Comment by andygrunwald** [comment]
Podcasts:
- https://logbuch-netzpolitik.de/
- https://alternativlos.org/

**Comment by woolfg** [comment]
podcastindex.org provides an api as well, maybe for basic data...

**Comment by andygrunwald** [comment]
Facts we can gather:
- First Episode
- Number of Episodes
- Hours of content
- Publishing cycle (weekly, monthly, ...) - calculated
- Avatar of the podcast
