### ISSUE TITLE
Google Search Console: Investigate Excluded pages on "Alternate page with proper canonical tag"

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#30]
Link: https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Aengineeringkiosk.dev&item_key=CAMYGCAC&hl=en

See
![screencapture-search-google-search-console-index-drilldown-2022-06-01-11_28_53](https://user-images.githubusercontent.com/320064/171373241-c4599367-329d-426a-8cc2-a8c395d8868b.png)

**Comment by woolfg** [comment]
the url with umlaute has another canonical as the umlaute are escaped in the canonical. but don't know what the problem of the others in the list is.

**Comment by andygrunwald** [comment]
After some tweaks, it looks quite good.
Most of the URLs were crawled in the past and need to be re-crawled.
For now, we keep it like this and observe the behavior.
