### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#5]
We need a logo for the new website.
The current logo of the new website can be found here: https://github.com/EngineeringKiosk/webpage/blob/main-website/public/images/logos/flex-ui-yellow-light.svg

Format of the new logo: SVG

**Comment by woolfg** [comment]
for the init launch I would propose to just use the mic from canva as orange svg and the text engineering kiosk

**Comment by andygrunwald** [comment]
Sure. I am open to everything here.
Just the format and size/dimensions should fit.

**Comment by andygrunwald** [comment]
First version from https://github.com/EngineeringKiosk/webpage/pull/1/commits/a2104fe2b8933b20a7b74e1bd791c8f911419da6

![Image](https://user-images.githubusercontent.com/320064/170831072-0b1eacd2-182b-4661-99ff-161b385a3356.png)
![Image](https://user-images.githubusercontent.com/320064/170831071-c0dff0a6-1401-444a-bea0-27ff5e76a0bc.png)

**Comment by andygrunwald** [comment]
The logo is good to go so far.
Closing it, because there is no concrete action.
