### ISSUE TITLE
Include AntennaPod

### ISSUE THREAD

**Issue by BaumiCoder** [EngineeringKiosk/webpage#544]
There is a possibility to make link for subscribing to a podcast in AntennaPod. The documentation for this is [here](https://antennapod.org/documentation/podcasters-hosters/add-on-antennapod). In the mentioned branding repository there the [logo as svg](https://github.com/AntennaPod/Branding/blob/master/Logo/logo-icon.svg) can be found.

Maybe such a link would suite in the [jetzt-folgen-Section](https://engineeringkiosk.dev/#jetzt-folgen) on the webpage.

**Comment by andygrunwald** [comment]
Thanks @BaumiCoder!

I will have a look into it - It can take a bit due to other obligations.

**Comment by andygrunwald** [comment]
@BaumiCoder I had a few minutes .- Can you check and test https://github.com/EngineeringKiosk/webpage/pull/545 ?
There is a preview link in the comments.

I can't test it, because I don't have an android phone.

Additionally: Do you know if there is a direct link to one particular episode also available? I was not able to find it quickly.

**Comment by BaumiCoder** [comment]
I tested the preview on my phone. The link leads a website of AntennaPod. There I can click a button to open / subscribe the podcast in the app :+1: 

I didn't know, if there is way to link to one particular episode in @AntennaPod .

**Comment by BaumiCoder** [comment]
Maybe one little thing should be changed: The linked website is in english. You can switch to german by changing antennapod.org to antennapod.org/de.

**Comment by andygrunwald** [comment]
@BaumiCoder Thanks a lot for this suggestion - This change is now online: https://engineeringkiosk.dev/#jetzt-folgen

If @AntennaPod comes back to us with a possibility of direct episode links, we can include this even in the detail episode view.
