### ISSUE TITLE
Transcript: Add Hover background color and a padding

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#582]
> - hover background color would be nice, maybe also a padding.

Example page: https://engineeringkiosk.dev/podcast/episode/94-die-realit%C3%A4t-des-freelancings-zwischen-selbstbestimmung-und-unsicherheit-mit-index-out-of-bounds/#transcript

This was feedback from https://github.com/EngineeringKiosk/webpage/pull/580

**Comment by woolfg** [comment]
closed by [965e536](https://github.com/EngineeringKiosk/webpage/commit/965e536bf0ab40c25a10edef5393bae83cfbda8a)
