### ISSUE TITLE
Transcript: Clickhandler sometimes throws an error

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#583]
On the page https://engineeringkiosk.dev/podcast/episode/94-die-realit%C3%A4t-des-freelancings-zwischen-selbstbestimmung-und-unsicherheit-mit-index-out-of-bounds/, we now have transcripts.

On each line, you can click to jump to the right section in the audio.
But sometimes, the clickhandler throws an error

<img width="1679" alt="Screenshot 2023-10-27 at 16 03 25" src="https://github.com/EngineeringKiosk/webpage/assets/320064/26512ac6-87a3-4fc2-844d-62713d795a0d">

**Comment by woolfg** [comment]
closed by [965e536](https://github.com/EngineeringKiosk/webpage/commit/965e536bf0ab40c25a10edef5393bae83cfbda8a)
