### ISSUE TITLE
Main image for the startpage

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#6]
We need a new main image for the startpage that fits the current design:

![Screenshot from 2022-05-16 23-05-08](https://user-images.githubusercontent.com/320064/168682496-f7215adb-9651-421b-b98b-8f682141c883.png)

The current image can be found here: https://github.com/EngineeringKiosk/webpage/blob/main-website/public/images/headers/header.jpg

**Comment by woolfg** [comment]
as mentioned in #2 image in front of kiosk holding mic & beer

**Comment by andygrunwald** [comment]
Version from https://github.com/EngineeringKiosk/webpage/pull/1/commits/82940e887211482e5314e51d0b6df226623fb3d0

![Image](https://user-images.githubusercontent.com/320064/170827562-0ef0b934-51df-4bf4-8ad7-e35ac7b5ace9.png)

**Comment by andygrunwald** [comment]
Second version from https://github.com/EngineeringKiosk/webpage/pull/1/commits/740c4934ae96515745d9255d3238396abbbcc566

![Image](https://user-images.githubusercontent.com/320064/170827935-1c9f8a73-9952-4bf4-a5f2-c650ef1498ac.png)
