### ISSUE TITLE
Move Social Links into a data.json file and re-use them

### ISSUE THREAD

**Issue by andygrunwald** [EngineeringKiosk/webpage#625]
We use the social links (e.g. TikTok) in multiple places already (Footer, `/linktree/`, etc.).
Lets unify this URL in one central place.
Similar like the spotify URL in `data.json`

**Comment by woolfg** [comment]
components to list the icons (just <li.) would be great. the component can be styled from outside. if we use a component we do not need a json file but can define verything in the compontent. 

but we have different types. like social media accounts and platforms. for platforms we can also have links to the episode itself. so we have to think a bit how we can structure that wisely. on e.g. linktree we also do not show all icons.
