### ISSUE TITLE
Improve SEO on tag listing pages and show more text including some keywords

### ISSUE THREAD

**Issue by woolfg** [EngineeringKiosk/webpage#85]
To have more text on the SEO tag listing pages and also reduce the probability to have duplicated content on it:

- [ ] Create Description for all tags and show it at the beginning
- [ ] Extend podcast description to see a bit more of the description (maybe also expand button to see more? could be then also used on all listing pages)

**Comment by andygrunwald** [comment]
Tags should have a
- long description
- short description

The short description should be used inside the meta tags for the single tag page
